name: Deploy to Archive Live Channel
'on':
  push:
    branches:
      - dmaorg-archive

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWENTYONEPILOTS_WIKI }}"
          projectId: 'twentyonepilots-wiki'
          target: 'dmaorg'
          channelId: live